# Dependencies
highlighter:      pygments

# Setup
title:             Lab Notebook
tagline:          'Tad Dallas'
description:      ''
baseurl:          /LabNotebook
paginate:         5

github:
  repo:           https://github.com/taddallas/LabNotebook
